require('./vue-resource')
require('./vue-scrollto')
require('./vue-bootstrap')
require('./vue-veevalidate')
require('./vue-bootrap-datepicker')
require('./vue-form-wizard')
require('./vue-simple-vue-validator')
